w/ working dynamic linker (helloworld-[no]lib.s)

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+SRC_DIR=./src/
+BUILD_DIR=./build/
+CWD=./
+
 abort() {
     echo ""
     echo "[Aborted] $@"
@@ -48,7 +52,14 @@ link() {
     return $out_status
 }
 
-
+linked() {
+    cd $BUILD_DIR
+    local out=$1
+    call "ld -m elf_i386 -dynamic-linker /lib/ld-linux.so.2 `object $@` -o $out -lc"
+    local out_status=$?
+    cd ../
+    return $out_status
+}
 
 build() {
     assembleMany $@
@@ -63,6 +74,10 @@ main() {
     case $fn in
         build)
             build $@
+            ;;
+        build-linked)
+            assembleMany $@
+            linked $@ || abort "Failed during linking step"
             ;;
         assemble)
             assembleMany $@
@@ -80,7 +95,7 @@ main() {
             build $@ && main exec $@
             ;;
         *)
-            echo $"Usage: ./run {simple|build|exec|link|assemble}"
+            echo $"Usage: ./run {simple|build|build-linked|exec|link|assemble}"
             exit 1
     esac
 
